[archetype.pickup_ammo]
description = "Ammo restoration pickup item"
components = ["transform", "sprite", "pickup", "script"]

[archetype.pickup_ammo.defaults.sprite]
texture = "sprites/pickup_ammo.png"
width = 0.5
height = 0.5
fullbright = true

[archetype.pickup_ammo.defaults.pickup]
pickup_type = "ammo"
amount = 15.0
range = 1.5

[archetype.pickup_ammo.defaults.script]
source = "pickup.rhai"
