[archetype.pickup_armor]
description = "Green armor pickup â€” provides 100 armor with 33% damage absorption"
components = ["transform", "sprite", "pickup", "script"]

[archetype.pickup_armor.defaults.sprite]
texture = "sprites/pickup_armor.png"
width = 0.8
height = 0.8
fullbright = true

[archetype.pickup_armor.defaults.pickup]
pickup_type = "armor"
amount = 100.0
range = 1.5

[archetype.pickup_armor.defaults.script]
source = "pickup.rhai"
