[archetype.pickup_weapon_shotgun]
description = "Shotgun weapon pickup"
components = ["transform", "sprite", "pickup", "script"]

[archetype.pickup_weapon_shotgun.defaults.sprite]
texture = "sprites/pickup_shotgun.png"
width = 0.6
height = 0.6
fullbright = true

[archetype.pickup_weapon_shotgun.defaults.pickup]
pickup_type = "weapon_shotgun"
amount = 8.0
range = 1.5

[archetype.pickup_weapon_shotgun.defaults.script]
source = "pickup.rhai"
