[package]
name = "flint-terrain"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
flint-core = { workspace = true }
image = { workspace = true }
